[package]
name = "termsize"
version = "0.1.0"
authors = ["softprops <d.tangren@gmail.com>"]
description = "Retrieves terminal size"
repository = "https://github.com/softprops/termsize"
homepage = "https://github.com/softprops/termsize"
documentation = "http://softprops.github.io/termsize"
keywords = ["tty", "terminal", "term", "size", "dimensions"]
license = "MIT"

[dependencies]
atty = "0.1"
libc = "0.2"
winapi = "0.2"
kernel32-sys = "0.2"