[package]
name = "termsize"
version = "0.1.4"
authors = ["softprops <d.tangren@gmail.com>"]
description = "Retrieves terminal size"
repository = "https://github.com/softprops/termsize"
homepage = "https://github.com/softprops/termsize"
documentation = "http://softprops.github.io/termsize"
keywords = ["tty", "terminal", "term", "size", "dimensions"]
license = "MIT"

[target.x86_64-apple-darwin.dependencies]
atty = "0.1"
libc = "0.2"

[target.i686-unknown-linux-gnu.dependencies]
atty = "0.1"
libc = "0.2"

[target.x86_64-unknown-linux-gnu.dependencies]
atty = "0.1"
libc = "0.2"

[target.arm-unknown-linux-gnueabihf.dependencies]
atty = "0.1"
libc = "0.2"

[target.armv7-unknown-linux-gnueabihf.dependencies]
atty = "0.1"
libc = "0.2"

[target.x86_64-unknown-fuchsia.dependencies]
atty = "0.1"
libc = "0.2"

[target.aarch64-unknown-fuchsia.dependencies]
atty = "0.1"
libc = "0.2"

[target.x86_64-pc-windows-msvc.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"

[target.i686-pc-windows-msvc.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"

[target.x86_64-pc-windows-gnu.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"

[target.i686-pc-windows-gnu.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"
